### ISSUE TITLE
JBC 마스토돈 (mstdn.jbc.ne.kr) 릴레이 승인요청

### ISSUE THREAD

**Issue by theakina** [mstdn-kr/kr-relay#11]
안녕하세요. JBC자유방송의 황명채입니다.
한국어권 연합우주를 알게되어 반갑습니다.

mstdn.jbc.ne.kr (서버(인스턴스)명 : JBC 마스토돈)의
릴레이 승인을 요청드립니다.

공식 이메일 : jbc@jbc.ne.kr
운영자 계정 : akina@mstdn.jbc.ne.kr

감사합니다.

끝.

**Comment by tribela** [comment]
Done!
