### ISSUE TITLE
플러피쉘터(fluffyshelter.day) 릴레이 승인요청

### ISSUE THREAD

**Issue by LievRenard** [mstdn-kr/kr-relay#12]
안녕하세요, 플러피쉘터 관리자 klarkatze입니다.

플러피쉘터(fluffyshelter.day)의 한국 인스턴스 연합 릴레이 참가를 신청합니다.

감사합니다.

관리자 이메일: aterapriey@gmail.com
관리자 계정: shelter@fluffyshelter.day

**Comment by tribela** [comment]
Done!
