### ISSUE TITLE
트잉여 대피소 릴레이 승인요청

### ISSUE THREAD

**Issue by cygnus6960** [mstdn-kr/kr-relay#13]
안녕하세요, 트잉여 대피소 관리자 cygnus6960입니다.

트잉여 대피소(https://twitshelter.hostdon.ne.jp/)의 한국 인스턴스 연합 릴레이 참가를 신청합니다.

추가로 말씀드리면, 사용자가 존재하는 한 계속 유지될 예정입니다. 
감사합니다.

관리자 이메일: [glacier.keeper@gmail.com](mailto:glacier.keeper@gmail.com)
관리자 계정: [cygnus6960@twitshelter.hostdon.ne.jp](mailto:cygnus6960@twitshelter.hostdon.ne.jp)

**Comment by tribela** [comment]
Done!
