### ISSUE TITLE
SiFNet Mastodon (social.silicon.moe) 릴레이 승인요청 

### ISSUE THREAD

**Issue by perillamint** [mstdn-kr/kr-relay#15]
안녕하세요, SiFNet Mastodon 관리자 perillamint 입니다.

SiFNet Mastodon (social.silicon.moe) 의 한국 인스턴스 연합 릴레이 참가를 신청합니다.

감사합니다.

관리자 이메일: [admin@silicon.moe](mailto:admin@silicon.moe)
관리자 계정: @admin@silicon.moe

**Comment by tribela** [comment]
Done!
