### ISSUE TITLE
bakedbean.xyz 릴레이 승인 요청 드립니다

### ISSUE THREAD

**Issue by su010423** [mstdn-kr/kr-relay#19]
개인 마스토돈 인스턴스 bakedbean.xyz 에 대한 릴레이 승인 요청 드립니다.

서버명 : bakedbean.xyz
소프트웨어명 : Mastodon
URL : https://bakedbean.xyz

감사합니다.

**Comment by unstabler** [comment]
추가 완료하였습니다. 감사합니다.
