### ISSUE TITLE
don.naru.cafe 승인 요청

### ISSUE THREAD

**Issue by sftblw** [mstdn-kr/kr-relay#20]
안녕하세요
버틸진 모르겠지만 사실상 1인 인스턴스인 don.naru.cafe 도 릴레이 화이트리스트 승인 요청을 드립니다.
나중에 인스턴스에서 릴레이 등록을 해지하면 이 쪽에서 구독 해지가 가능하려나요...? 단순 화이트리스트가 아니라 등록 해지에도 별도 절차가 필요하다면 그냥 이슈를 닫아주시면 감사하겠습니다.

* https://don.naru.cafe (웹 주소와 핸들 주소 동일)
* Mastodon 3.4.3

**Comment by unstabler** [comment]
추가하였습니다.
화이트리스트에만 추가하는 것이기 떄문에 해지는 그냥 등록 해지 해주시면 됩니다.
