### ISSUE TITLE
am.sakede.su 승인 요청

### ISSUE THREAD

**Issue by sake2054** [mstdn-kr/kr-relay#23]
서버명 : 🍶사케(아직 1인 인스턴스입니다...ㅠ)
소프트웨어명 : mastodon 3.5.3
Web 주소 : https://am.sakede.su

**Comment by unstabler** [comment]
등록 완료하였습니다.

**Comment by sake2054** [comment]
감사합니다. 릴레이 목록에 추가했는데 계속 승인 대기중이라고 되어 있어 질문 드립니다. 혹시 릴레이 주소가 `http://relay.mastodon.kr/inbox` 가 맞을까요?

**Comment by unstabler** [comment]
네, 맞습니다. 혹시 릴레이 등록 제거 후 다시 시도를 부탁드려도 될까요?

**Comment by sake2054** [comment]
`https://relay.mastodon.kr/inbox`를 추가하니 작동했습니다. 감사합니다!!
