### ISSUE TITLE
twt.rs 릴레이 승인 요청

### ISSUE THREAD

**Issue by finalchild** [mstdn-kr/kr-relay#26]
서버명: twt.rs
소프트웨어명: Misskey
Web 주소: https://twt.rs/
핸들 주소: https://twt.rs/

릴레이 가입 요청드립니다!

**Comment by unstabler** [comment]
등록 완료하였습니다.

`https://relay.mastodon.kr/actor` 를 릴레이 주소로 등록하시길 바랍니다.
