### ISSUE TITLE
sns.dun.land 릴레이 등록 요청

### ISSUE THREAD

**Issue by dungsil** [mstdn-kr/kr-relay#31]
안녕하세요 릴레이 등록 요청드립니다.

  -  서버명: DUN LAND
  -  소프트웨어명: 마스토돈 v4.0.2
  -  Web 주소 : https://sns.dun.land
  -  (웹 주소와 핸들 주소가 다르다면) 핸들 주소 : dun.land

**Comment by unstabler** [comment]
추가하였습니다! https://relay.mastodon.kr/inbox 를 릴레이 주소로 추가해 주세요.
