### ISSUE TITLE
gogu.ma 릴레이 승인 요청

### ISSUE THREAD

**Issue by elpw** [mstdn-kr/kr-relay#32]
안녕하세요. gogu.ma 인스턴스의 릴레이 승인 요청 드립니다.

   - 서버명: gogu.ma
   - 소프트웨어명: Mastodon
   - Web 주소: `mstdn.gogu.ma`
   - 핸들 주소: `gogu.ma`

**Comment by unstabler** [comment]
추가하였습니다! https://relay.mastodon.kr/inbox 를 릴레이 주소로 추가해 주세요.
