### ISSUE TITLE
mastodon.aioo.ooo 릴레이 승인 요청

### ISSUE THREAD

**Issue by AiOO** [mstdn-kr/kr-relay#35]
- 서버명: AiOO's Mastodon
- 소프트웨어명: Mastodon 4.0.2
- Web 주소: mastodon.aioo.ooo
- (웹 주소와 핸들 주소가 다르다면) 핸들 주소: aioo.ooo

잘 부탁드립니다. 노고에 감사드립니다.

**Comment by unstabler** [comment]
추가하였습니다! https://relay.mastodon.kr/inbox 를 릴레이 주소로 추가해 주세요.
