### ISSUE TITLE
dlun.ch 릴레이 가입 신청서

### ISSUE THREAD

**Issue by dlunch** [mstdn-kr/kr-relay#40]
- 서버명: dlun.ch
- 소프트웨어명: Mastodon 4.0.2
- 웹 주소: https://dlun.ch
- 핸들 주소 (웹 주소와 다를시 기재):

**Comment by unstabler** [comment]
추가하였습니다! https://relay.mastodon.kr/inbox 를 릴레이 주소로 추가해 주세요.
