### ISSUE TITLE
hyperpla.net 릴레이 가입 신청서

### ISSUE THREAD

**Issue by park012241** [mstdn-kr/kr-relay#41]
- 서버명: hyperpla.net
- 소프트웨어명: Mastodon
- 웹 주소: https://hyperpla.net
- 핸들 주소 (웹 주소와 다를시 기재): https://hyperpla.net (동일)

릴레이 가입 요청 드립니다!

**Comment by unstabler** [comment]
추가하였습니다! https://relay.mastodon.kr/inbox 를 릴레이 주소로 추가해 주세요.
