### ISSUE TITLE
m.tirr.dev 릴레이 가입 신청서

### ISSUE THREAD

**Issue by tirr-c** [mstdn-kr/kr-relay#42]
- 서버명: Tirr
- 소프트웨어명: Mastodon
- 웹 주소: https://m.tirr.dev
- 핸들 주소 (웹 주소와 다를시 기재): tirr.dev

**Comment by unstabler** [comment]
추가하였습니다! https://relay.mastodon.kr/inbox 를 릴레이 주소로 추가해 주세요.

**Comment by tirr-c** [comment]
@unstabler 릴레이가 승인 대기 중 상태에 머물러 있는데, 제가 추가로 진행해야 할 것이 있을까요?

**Comment by unstabler** [comment]
@tirr-c 
- 혹시 제거 후 다시 등록을 시도해봐주실 수 있으신가요? (Mastodon의 경우 `/actor` 대신 `/inbox` 를 릴레이 주소로 추가할 필요가 있습니다)

**Comment by unstabler** [comment]
연결된 인스턴스 목록에서는 정상적으로 표시되고 있는 것 같습니다!

**Comment by tirr-c** [comment]
활성화됐습니다! 감사합니다.
