### ISSUE TITLE
[chalk.moe] 릴레이 가입 신청서

### ISSUE THREAD

**Issue by chalkpe** [mstdn-kr/kr-relay#45]
### 서버명

Chalkboard

### 소프트웨어명

[Mastodon 4.0.2](https://github.com/glitch-soc/mastodon/)

### 웹 주소

[`chalk.moe`](https://chalk.moe)

### 핸들 주소

[`chalk.moe`](https://chalk.moe) (동일)

**Comment by unstabler** [comment]
등록 완료하였습니다. https://relay.mastodon.kr/ 내에 기재된 안내를 따라 릴레이 설정을 완료해 주세요.
