### ISSUE TITLE
[t.chadole.com] 릴레이 가입 신청서

### ISSUE THREAD

**Issue by taylor224** [mstdn-kr/kr-relay#46]
### 서버명

차돌이

### 소프트웨어명

mastodon 4.0.2

### 웹 주소

https://t.chadole.com

### 핸들 주소

https://t.chadole.com

**Comment by unstabler** [comment]
등록 완료하였습니다. https://relay.mastodon.kr/ 내에 기재된 안내를 따라 릴레이 설정을 완료해 주세요.
