### ISSUE TITLE
[constellati.one] 릴레이 가입 신청서

### ISSUE THREAD

**Issue by Nebu1eto** [mstdn-kr/kr-relay#47]
### 서버명

별자리

### 소프트웨어명

Mastodon 4.0.2+glitch

### 웹 주소

https://constellati.one

### 핸들 주소

https://constellati.one

**Comment by tribela** [comment]
등록 완료했습니다 (문제 없으면 닫아주시고 문제 있으면 댓글 더 달아주세요)
