### ISSUE TITLE
[pub.eeruwang.me] 릴레이 가입 신청서

### ISSUE THREAD

**Issue by eeruwang** [mstdn-kr/kr-relay#48]
### 서버명

이루왕 펍

### 소프트웨어명

Mastodon 4.0.2

### 웹 주소

pub.eeruwang.me

### 핸들 주소

pub.eeruwang.me

**Comment by unstabler** [comment]
등록 완료하였습니다. https://relay.mastodon.kr/ 내에 기재된 안내를 따라 릴레이 설정을 완료해 주세요.
