### ISSUE TITLE
[renkontu.com] 릴레이 가입 신청서

### ISSUE THREAD

**Issue by renkontu** [mstdn-kr/kr-relay#49]
### 서버명

Renkontu(렌콘투)

### 소프트웨어명

Mastodon v4.0.2

### 웹 주소

https://renkontu.com

### 핸들 주소

https://renkontu.com

**Comment by unstabler** [comment]
등록 완료하였습니다. https://relay.mastodon.kr/ 내에 기재된 안내를 따라 릴레이 설정을 완료해 주세요.
