### ISSUE TITLE
ivory.rosebloom.one 릴레이 가입 신청서

### ISSUE THREAD

**Issue by RBrosebud** [mstdn-kr/kr-relay#52]
### 서버명
ivory.rosebloom.one (nginx 서버명)
RB ivory (마스토돈 내 서버 이름)

### 소프트웨어명

mastodon v4.0.2

### 웹 주소

ivory.rosebloom.one

### 핸들 주소

rosebloom.one

지인제 소규모 서버이지만 혼자 사용하는 게 아닌 다른 지인들의 가입을 염두에 두고 있는 서버입니다. 이 경우에도 승인이 될까요?

**Comment by RBrosebud** [comment]
지인제 소규모 서버이지만 혼자 사용하는 게 아닌 다른 지인들의 가입을 염두에 두고 있는 서버입니다. 이 경우에도 승인이 될까요?

**Comment by unstabler** [comment]
등록 완료하였습니다. https://relay.mastodon.kr/ 내에 기재된 안내를 따라 릴레이 설정을 완료해 주세요.

> 지인제 소규모 서버이지만 혼자 사용하는 게 아닌 다른 지인들의 가입을 염두에 두고 있는 서버입니다. 이 경우에도 승인이 될까요?

릴레이 가입이 가능합니다만 특정 주제로 한정되어 있는 인스턴스이신 경우 연합 타임라인에 원하지 않는 주제의 내용이 표시될 수 있습니다.
