### ISSUE TITLE
twt.rs의 cloudflare 뒤 도메인 추가 요청

### ISSUE THREAD

**Issue by finalchild** [mstdn-kr/kr-relay#53]
#26 으로 릴레이 allowlist에 포함되었으나, cloudflare 뒤 도메인을 넣지 않았습니다.
raw.twt.rs 추가를 요청드립니다.

**Comment by unstabler** [comment]
반영 완료하였습니다! 늦어져서 죄송합니다.

**Comment by tribela** [comment]
이것 때문에 릴레이가 깨져 있었군요. 도메인을 그렇게 넣으면 안 됩니다. 실제 서비스 하는 도메인을 넣어야 합니다

**Comment by finalchild** [comment]
아직 추가가 되지 않습니다.

https://github.com/mstdn-kr/kr-relay/blob/master/acl.txt

이 파일에 있는 도메인들과 같은 방식으로 추가된 게 맞을까요?

**Comment by tribela** [comment]
그건 아예 안 쓰는 다른 소프트웨어입니다. 릴레이 메인페이지에 있는 매뉴얼에 따라 제대로 된 방법으로 릴레이를 추가하면 됩니다

**Comment by finalchild** [comment]
추가 자체는 제대로 한 것 같습니다. inbox와 actor를 동시에 추가히는 것도 시도해 보았습니다.
