### ISSUE TITLE
REQUEST: add toot.funami.tech to allowlist

### ISSUE THREAD

**Issue by NoaHimesaka1873** [mstdn-kr/kr-relay#6]
제목 그대로 toot.funami.tech을 allowlist에 추가를 요청합니다

**Comment by tribela** [comment]
웹 도메인은 toot.funami.tech이고 실제 AP용으로 사용하는 도메인은 funami.tech인 것 같네요. 일단 후자로 추가해보겠습니다

**Comment by tribela** [comment]
연동 안 되면 다시 코멘트 주세요. toot.funami.tech로 수정해 드리겠습니다
@NoaHimesaka1873

**Comment by NoaHimesaka1873** [comment]
@tribela 현재 승인 대기중이라고만 뜹니다

**Comment by tribela** [comment]
@NoaHimesaka1873 toot.funami.tech로 변경했으니 관리자 패널에서 릴레이를 삭제 후 재등록 해보세요. (그 후 새로고침까지 해야 됩니다)

**Comment by NoaHimesaka1873** [comment]
@tribela 재등록 하고 좀 기다리고 새로고침하고 해도 여전하네요.
![image](https://user-images.githubusercontent.com/39993457/196101357-15800197-23d7-4255-bb55-98177722fe4c.png)

**Comment by tribela** [comment]
@NoaHimesaka1873 그럼 둘 다 추가했으니 다시 해보시기 바랍니다.
그래도 안 되면 릴레이 소프트웨어가 지원하지 않는 것입니다.

**Comment by NoaHimesaka1873** [comment]
@tribela 오 이제 되네요 도움 감사합니다.

**Comment by NoaHimesaka1873** [comment]
@tribela 연결이 끊긴 거 같은데 뭔가요?

**Comment by NoaHimesaka1873** [comment]
Nevermind, URL changed.
